apiVersion: v1
kind: Service
metadata:
  name: fastapi-auth-service
  namespace: todo-project
  labels:
    app: fastapi-auth
spec:
  selector:
    app: fastapi-auth
  ports:
    - port: 8002
      targetPort: 8002