apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: todo-project
spec:
  selector:
    app: postgres-auth
  ports:
    - name: postgres-auth
      port: 5432
      targetPort: 5432
