apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth-deployment
  namespace: todo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
      - name: postgres-auth
        image: postgres:14
        envFrom:
          - secretRef:
              name: postgres-auth-secret
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
          - name: postgres-auth-volume-mount
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-auth-volume-mount
          persistentVolumeClaim:
            claimName: postgres-auth-pvc
