kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-auth-pvc
  namespace: todo-project
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-auth-pv