apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-project
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          envFrom:
            - secretRef:
                name: core-kafka-secret
          image: confluentinc/cp-kafka:latest
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:9092"
          ports:
            - containerPort: 9092
#          ports:
#            - containerPort: 29092
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: data
          emptyDir: {}