apiVersion: v1
kind: Service
metadata:
  namespace: todo-project
  name: kafka-services
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
#    todo: incorrect port, replace by 29092
    - name: kafka
      port: 9092
      targetPort: 9092
