#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: todo-project
#  name: zookeeper
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: zookeeper
#  strategy: {}
#  template:
#    metadata:
#      - name: zookeeper
#    spec:
#      containers:
#        - name: zookeeper
#          envFrom:
#            - secretRef:
#                name: zookeeper-secret
#          image: confluentinc/cp-zookeeper:latest
#          ports:
#            - containerPort: 22181
#          resources: {}
#      restartPolicy: Always
#status: {}


apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-project
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          envFrom:
            - secretRef:
                name: zookeeper-secret
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
